
-- Supabase 数据库表结构
-- 创建鸡尾酒卡片表
CREATE TABLE IF NOT EXISTS cocktail_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  bar_name TEXT NOT NULL,
  drink_name TEXT,
  base_spirit TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  review TEXT,
  date DATE NOT NULL,
  image_data TEXT,
  rating INTEGER DEFAULT 0,
  user_id UUID REFERENCES auth.users(id)
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_cocktail_cards_user_id ON cocktail_cards(user_id);
CREATE INDEX IF NOT EXISTS idx_cocktail_cards_date ON cocktail_cards(date DESC);

-- 启用行级安全 (RLS)
ALTER TABLE cocktail_cards ENABLE ROW LEVEL SECURITY;

-- 创建安全策略 - 用户只能访问自己的数据
CREATE POLICY "Users can view their own cards"
  ON cocktail_cards
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own cards"
  ON cocktail_cards
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own cards"
  ON cocktail_cards
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own cards"
  ON cocktail_cards
  FOR DELETE
  USING (auth.uid() = user_id);

-- 创建存储桶用于图片
INSERT INTO storage.buckets (id, name)
VALUES ('cocktail-images', 'cocktail-images')
ON CONFLICT (id) DO NOTHING;

-- 设置存储桶权限
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING (bucket_id = 'cocktail-images');

CREATE POLICY "Authenticated Users Can Upload"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'cocktail-images' AND
  auth.uid() IS NOT NULL
);

CREATE POLICY "Users Can Update Their Own"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'cocktail-images' AND
  auth.uid() = owner
);

CREATE POLICY "Users Can Delete Their Own"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'cocktail-images' AND
  auth.uid() = owner
);

